owner: rdpstudio2019
repo: monitor

sites:
  - name: ID 方糖通行证
    url: $ID_HEALTH
  - name: Community 方糖社区
    url: https://com.rdpstudio.top
  - name: HyperChat
    url: $HYPERCHAT_HEALTH
  - name: CoreTree 核心树
    url: $CORETREE_HEALTH
  - name: AutoPatch 下载服务器
    url: $AUTOPATCH_HEALTH
  - name: HiNet Link API
    url: $HINETLINK_HEALTH

status-website:
  cname: monitor.rdpstudio.top
  logoUrl: https://webstatic.rdpstudio.top/cn/fangtang-cn-footer/resource/logo.png
  name: 方糖网络科技状态站
  introTitle: 方糖网络科技状态站
  introMessage: 方糖网络科技服务运行状态监控
  navbar:
    - title: 状态站
      href: /
    - title: 通行证用户中心
      href: https://id.rdpstudio.top
