# Change these first
owner: rdpstudio2019
repo: monitor

sites:
  - name: ID 方糖通行证
    url: https://id.rdpstudio.top/api/v1/health
  - name: Community 方糖社区
    url: https://com.rdpstudio.top
  - name: HyperChat
    url: https://hyperchat.rdpstudio.top/.well-known/matrix/client
  - name: CoreTree 核心树
    url: https://api-coretree.rdpstudio.top/api/v1/health
  - name: AutoPatch 下载服务器
    url: https://autopatch.rdpstudio.top
  - name: HiNet Link API
    url: https://hinet_link_api.rdpstudio.top

status-website:
  cname: status.rdpstudio.top
  logoUrl: https://webstatic.rdpstudio.top/cn/fangtang-cn-footer/resource/logo.png
  name: 方糖网络科技状态站
  introTitle: 方糖网络科技状态站
  introMessage: 方糖网络科技服务运行状态监控
  navbar:
    - title: 状态站
      href: /
    - title: 通行证用户中心
      href: https://id.rdpstudio.top
